package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"pos-backend/middleware"
	"pos-backend/routes"
	categorias "pos-backend/services/categorias"
	productos "pos-backend/services/productos"

	"cloud.google.com/go/firestore"
	"github.com/gorilla/mux"
	"google.golang.org/api/option"

	_ "pos-backend/docs" // docs is generated by Swag CLI, you have to import it.

	httpSwagger "github.com/swaggo/http-swagger/v2"
)

var (
	credentialPath = "credentials.json"
	projectId      = "lumo-pos"
)

// @title LUMO POS API
// @description API para el sistema de punto de venta LUMO POS
// @version 1.0
// @host localhost:8000
// @BasePath /
// @schemes http
// @produce json
// @consumes json
func main() {
	// Inicializar la app de Firebase
	ctx := context.Background()
	opt := option.WithCredentialsFile(credentialPath)
	app, err := firestore.NewClient(ctx, projectId, opt)
	if err != nil {
		log.Fatalf("Error al crear el cliente de Firestore: %v", err)
	}
	defer app.Close() // Cerrar el cliente de Firestore al salir de main()

	fmt.Println("Firebase inicializado correctamente")

	// Configurar enrutador
	router := mux.NewRouter()

	// Configurar middleware para registrar la IP del cliente en todos los manejadores de rutas
	router.Use(middleware.LogStatusMiddleware)

	// Configurar productos service
	productService := productos.NewProductServiceFirestore(app, ctx)

	// Configurar categorías service
	categoryService := categorias.NewCategoryServiceFirestore(app, ctx)
	// Configurar rutas
	routes.SetCategoriasRoutes(router, categoryService)
	routes.SetProductosRoutes(router, productService)

	// Configurar ruta de prueba
	router.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, "Up and running...")
	})

	// Configurar ruta de documentación
	router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)

	// Configurar servidor HTTP
	const port = ":8000"
	server := &http.Server{
		Addr:    port,
		Handler: router,
	}

	// Iniciar servidor HTTP
	log.Println("Server running on port", port)
	log.Fatalln(server.ListenAndServe())
}
